// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"Constants","status":true,"description":"Set of constants used to avoid magic numbers in the code.","parameters":{}},
{"name":"Utils","status":true,"description":"Contains utility functions, such as assert() and printObject()","parameters":{}},
{"name":"Skills","status":true,"description":"Plugin that implements some unconventional skills for actors.","parameters":{}},
{"name":"View","status":true,"description":"Plugin for adding visual effects to fighting system.","parameters":{}},
{"name":"CustomChoicesWindow","status":true,"description":"A window that displays some choices, and has an area to display some text next to the choices.","parameters":{}},
{"name":"WerewolvesSkills","status":true,"description":"Plugin containing custom Werewolves effects.","parameters":{}},
{"name":"HealthBar","status":true,"description":"Plugin to display enemies health bars.","parameters":{}},
{"name":"CustomShop","status":true,"description":"A way to add item limits to the shop.","parameters":{}},
{"name":"Bgs_MenusCancelCommand","status":true,"description":"Add a cancel command to menus of your choice","parameters":{"Cancel Command Name":"← Back","Include in Main Menu":"true","Include in Item":"true","Include in Skill":"true","Include in Equip":"true","Include in Status":"true","Include in Options":"true","Include in Save":"true","Include in Party":"true","Include in Shop":"true"}},
{"name":"MobileMenuButton","status":true,"description":"A plugin to add a menu button in the mobile version of the project.","parameters":{}},
{"name":"StatusPicker","status":true,"description":"Plugin used to extract statuses from actors","parameters":{}},
{"name":"JellyfishSkills","status":true,"description":"Custom skills for Jellyfish.","parameters":{}}
];
